#!/bin/sh

PROJECT=chiefimage

if [ $# != 1 ]; then
    echo "USAGE:    $0 tag"
    exit 1
fi
tag=$1

dir=/tmp/deploy-$PROJECT-$$
mkdir -p $dir

set -x
cd $dir
git clone git@github.com:eobrain/$PROJECT.git
cd $PROJECT
git pull --tags
git checkout $tag
git status

cmd="make  VERSION=$tag  appengine"
read -p "<ENTER> to '$cmd', or <CTRL>-C to abort" dummy
$cmd
